### PR TITLE
Add AMR gradio demo

### PR DESCRIPTION
**Pull request by h-munakata**
# Summary
- Add AMR gradio demo
- Rename old demo

### CODE REVIEW

**Comment by awkrail** [comment]
Thank you for your contribution. Could you change mr_hd_demo.py to demo.py to align it with api_example/ ?

**Comment by h-munakata** [comment]
I'm sorry for my forgetting. I fixed it.

**Comment by awkrail** [comment]
Thank you for your contribution. I merged it.

**Comment by awkrail** [comment]
This will be included in the next v1.1

**Pull request merged**
